# Here you can configure your own Continuous Integration script
# Maybe create a registry image with the back-end install, to avoid installing ever

stages:
  - some_stage

some_job:
  stage: some_stage
  script:
  # Install osp-core
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cc-asp.fraunhofer.de/simphony/osp-core
    - cd osp-core
    - python3 setup.py install -o ../some/ontology/maybe.yml
    - cd ..
  # Other stuff
    - install_some_things
    - run_other_things
    - testing_and_coverage_too